backend:
  name: github
  repo: casjr13/thischristography
  branch: gatsby

media_folder: static/assets
public_folder: /assets

collections:
  - name: collection
    label: Collection
    folder: collection
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, required: true }
      - { name: caption, label: Caption, required: true }
      - { name: image, label: Image, widget: image, required: true }
