backend:
  name: github
  repo: casjr13/thischristography
  branch: gatsby

media_folder: static/assets
public_folder: /assets

collections:
  - name: collection
    label: Collection
    folder: collections
    create: true
    slug: index
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { name: title, label: Title, required: true }
      - { name: caption, label: Caption, required: true }
      - {
          name: thumbnail,
          label: Featured Image,
          widget: image,
          required: true,
          allow_multiple: false,
          choose_url: false
        }
